import { Product } from '../types';

export const productsData: Product[] = [
  {
    id: '1',
    name: 'MacBook Pro M3',
    description: 'Ordinateur portable Apple MacBook Pro avec puce M3, écran Retina 14 pouces, 16GB RAM, 512GB SSD. Performance exceptionnelle pour les professionnels créatifs.',
    price: 2299,
    originalPrice: 2499,
    image: 'https://images.pexels.com/photos/812264/pexels-photo-812264.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: 'Informatique',
    subcategory: 'Ordinateurs portables',
    brand: 'Apple',
    rating: 4.8,
    reviews: 245,
    inStock: true,
    tags: ['apple', 'macbook', 'ordinateur', 'portable', 'm3'],
    featured: true,
    isNew: true,
    discount: 8
  },
  {
    id: '2',
    name: 'iPhone 15 Pro',
    description: 'Le dernier iPhone avec puce A17 Pro, appareil photo professionnel et écran Super Retina XDR. Design en titane premium.',
    price: 1199,
    image: 'https://images.pexels.com/photos/699122/pexels-photo-699122.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: 'Smartphones',
    subcategory: 'iPhone',
    brand: 'Apple',
    rating: 4.9,
    reviews: 532,
    inStock: true,
    tags: ['iphone', 'apple', 'smartphone', '15 pro'],
    featured: true,
    isNew: true
  },
  {
    id: '3',
    name: 'Samsung Galaxy S24 Ultra',
    description: 'Smartphone Android premium avec S Pen intégré, appareil photo 200MP et écran Dynamic AMOLED 6.8 pouces.',
    price: 1099,
    originalPrice: 1299,
    image: 'https://images.pexels.com/photos/1092644/pexels-photo-1092644.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: 'Smartphones',
    subcategory: 'Android',
    brand: 'Samsung',
    rating: 4.7,
    reviews: 387,
    inStock: true,
    tags: ['samsung', 'galaxy', 'android', 's24', 'ultra'],
    featured: true,
    discount: 15
  },
  {
    id: '4',
    name: 'Sony WH-1000XM5',
    description: 'Casque audio sans fil avec réduction de bruit active industry-leading, autonomie 30h, son haute résolution.',
    price: 399,
    originalPrice: 449,
    image: 'https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: 'Audio',
    subcategory: 'Casques',
    brand: 'Sony',
    rating: 4.8,
    reviews: 892,
    inStock: true,
    tags: ['sony', 'casque', 'bluetooth', 'noise-cancelling'],
    discount: 11
  },
  {
    id: '5',
    name: 'AirPods Pro 2',
    description: 'Écouteurs sans fil Apple avec réduction de bruit adaptative, son spatial personnalisé et boîtier de charge MagSafe.',
    price: 279,
    image: 'https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: 'Audio',
    subcategory: 'Écouteurs',
    brand: 'Apple',
    rating: 4.6,
    reviews: 1243,
    inStock: true,
    tags: ['airpods', 'apple', 'écouteurs', 'bluetooth']
  },
  {
    id: '6',
    name: 'Dell XPS 13',
    description: 'Ultrabook premium avec processeur Intel Core i7, écran InfinityEdge 13.4 pouces, design ultra-fin.',
    price: 1499,
    originalPrice: 1699,
    image: 'https://images.pexels.com/photos/7974/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=500',
    category: 'Informatique',
    subcategory: 'Ordinateurs portables',
    brand: 'Dell',
    rating: 4.5,
    reviews: 156,
    inStock: true,
    tags: ['dell', 'xps', 'ultrabook', 'intel'],
    discount: 12
  },
  {
    id: '7',
    name: 'Nintendo Switch OLED',
    description: 'Console de jeu hybride avec écran OLED 7 pouces, joy-cons améliorés, dock avec port Ethernet.',
    price: 349,
    image: 'https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: 'Gaming',
    subcategory: 'Consoles',
    brand: 'Nintendo',
    rating: 4.7,
    reviews: 678,
    inStock: true,
    tags: ['nintendo', 'switch', 'console', 'oled', 'gaming']
  },
  {
    id: '8',
    name: 'iPad Air M2',
    description: 'Tablette Apple avec puce M2, écran Liquid Retina 10.9 pouces, compatible Apple Pencil et Magic Keyboard.',
    price: 699,
    originalPrice: 799,
    image: 'https://images.pexels.com/photos/1334597/pexels-photo-1334597.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: 'Tablettes',
    subcategory: 'iPad',
    brand: 'Apple',
    rating: 4.8,
    reviews: 423,
    inStock: true,
    tags: ['ipad', 'apple', 'tablette', 'm2', 'air'],
    discount: 13
  },
  {
    id: '9',
    name: 'Canon EOS R6 Mark II',
    description: 'Appareil photo hybride plein format 24MP, stabilisation 8 stops, vidéo 4K 60p, pour photographes professionnels.',
    price: 2499,
    image: 'https://images.pexels.com/photos/90946/pexels-photo-90946.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: 'Photo',
    subcategory: 'Appareils photo',
    brand: 'Canon',
    rating: 4.9,
    reviews: 187,
    inStock: true,
    tags: ['canon', 'eos', 'appareil photo', 'hybride', 'plein format'],
    featured: true
  },
  {
    id: '10',
    name: 'Apple Watch Series 9',
    description: 'Montre connectée avec puce S9, écran Always-On Retina, suivi santé avancé, résistance à l\'eau 50m.',
    price: 449,
    image: 'https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: 'Wearables',
    subcategory: 'Montres connectées',
    brand: 'Apple',
    rating: 4.6,
    reviews: 756,
    inStock: true,
    tags: ['apple watch', 'montre connectée', 'santé', 'fitness'],
    isNew: true
  },
  {
    id: '11',
    name: 'Samsung 55" Neo QLED 4K',
    description: 'Téléviseur 55 pouces avec technologie Quantum Matrix, processeur Neo Quantum 4K, HDR 10+, Smart TV Tizen.',
    price: 1299,
    originalPrice: 1599,
    image: 'https://images.pexels.com/photos/1201996/pexels-photo-1201996.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: 'TV & Home Cinema',
    subcategory: 'Téléviseurs',
    brand: 'Samsung',
    rating: 4.7,
    reviews: 234,
    inStock: true,
    tags: ['samsung', 'tv', 'qled', '4k', '55 pouces'],
    discount: 19
  },
  {
    id: '12',
    name: 'Dyson V15 Detect',
    description: 'Aspirateur sans fil avec détection laser de la poussière, puissance d\'aspiration 230 AW, autonomie 60 min.',
    price: 749,
    originalPrice: 849,
    image: 'https://images.pexels.com/photos/4239032/pexels-photo-4239032.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: 'Électroménager',
    subcategory: 'Aspirateurs',
    brand: 'Dyson',
    rating: 4.8,
    reviews: 567,
    inStock: true,
    tags: ['dyson', 'aspirateur', 'sans fil', 'v15', 'detect'],
    discount: 12
  }
];

export const categories = [
  { id: 'informatique', name: 'Informatique', subcategories: ['Ordinateurs portables', 'PC de bureau', 'Composants'] },
  { id: 'smartphones', name: 'Smartphones', subcategories: ['iPhone', 'Android', 'Accessoires'] },
  { id: 'audio', name: 'Audio', subcategories: ['Casques', 'Écouteurs', 'Enceintes'] },
  { id: 'gaming', name: 'Gaming', subcategories: ['Consoles', 'Jeux', 'Accessoires'] },
  { id: 'tablettes', name: 'Tablettes', subcategories: ['iPad', 'Android', 'Windows'] },
  { id: 'photo', name: 'Photo', subcategories: ['Appareils photo', 'Objectifs', 'Accessoires'] },
  { id: 'wearables', name: 'Wearables', subcategories: ['Montres connectées', 'Fitness trackers'] },
  { id: 'tv', name: 'TV & Home Cinema', subcategories: ['Téléviseurs', 'Barres de son', 'Projecteurs'] },
  { id: 'electromenager', name: 'Électroménager', subcategories: ['Aspirateurs', 'Cuisine', 'Linge'] }
];